version: 2
updates:
  - package-ecosystem: "pip"
    # Location of package manifests
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      timezone: "America/Sao_Paulo"
