name: "Continuos Integration"

on:
  push:
    branches: [ "master", "feature/**", "hotfix/**" ]
  pull_request:
    types: [ "opened" ]
    branches: [ "!master" ]

env:
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.6
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.6"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest faker coverage pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f development/requirements.txt ]; then pip install -r development/requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest --cov-config=.coveragerc --cov-report=xml --doctest-modules --cov=. app/
      - name: Archive coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage.xml

  sonar-cloud:
    name: Analyzing code quality with SonarCloud
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test coverage file download
        uses: actions/download-artifact@v3
      - name: Moving coverage file to correct folder
        shell: bash
        run: |
          sed -i 's+/home/runner/work/${{env.REPOSITORY_NAME}}/${{env.REPOSITORY_NAME}}+/github/workspace+g' code-coverage-report/coverage.xml
      - uses: SonarSource/sonarcloud-github-action@master
